<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Writing functions – R Best Practices</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./writing-a-reprex-getting-unstuck.html" rel="next">
<link href="./writing-readable-code.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b45b7b0fa9169e986df15f1ef60a279c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1815a5215514b86a9dbfb465bf846045.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./writing-functions.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Writing functions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R Best Practices</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/njtierney/rbestpractices" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./R-Best-Practices.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project-organisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Project organisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code-style-and-readability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Code style and readability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing-readable-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Writing readable code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing-functions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Writing functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing-a-reprex-getting-unstuck.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Writing a reprex / getting unstuck</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-designing-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Designing functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-anonymous-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Anonymous functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-speed-of-thought.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Working closer to the speed of thought</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-pipes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">How `|&gt;` differs from `%&gt;%`</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-curly-braces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">What <code>{}</code> really does</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#the-problem-functions-solve" id="toc-the-problem-functions-solve" class="nav-link" data-scroll-target="#the-problem-functions-solve"><span class="header-section-number">4.1</span> The problem functions solve</a></li>
  <li><a href="#anatomy-of-a-function" id="toc-anatomy-of-a-function" class="nav-link" data-scroll-target="#anatomy-of-a-function"><span class="header-section-number">4.2</span> Anatomy of a function</a>
  <ul class="collapse">
  <li><a href="#naming-a-function" id="toc-naming-a-function" class="nav-link" data-scroll-target="#naming-a-function">Naming a function</a></li>
  <li><a href="#arguments-and-where-their-values-come-from" id="toc-arguments-and-where-their-values-come-from" class="nav-link" data-scroll-target="#arguments-and-where-their-values-come-from">Arguments, and where their values come from</a></li>
  </ul></li>
  <li><a href="#other-things-worth-turning-into-a-function" id="toc-other-things-worth-turning-into-a-function" class="nav-link" data-scroll-target="#other-things-worth-turning-into-a-function"><span class="header-section-number">4.3</span> Other things worth turning into a function</a></li>
  <li><a href="#how-to-use-a-debugger" id="toc-how-to-use-a-debugger" class="nav-link" data-scroll-target="#how-to-use-a-debugger"><span class="header-section-number">4.4</span> How to use a debugger</a>
  <ul class="collapse">
  <li><a href="#a-good-case-for-a-debugger" id="toc-a-good-case-for-a-debugger" class="nav-link" data-scroll-target="#a-good-case-for-a-debugger">A good case for a debugger</a></li>
  <li><a href="#debugging-with-browser" id="toc-debugging-with-browser" class="nav-link" data-scroll-target="#debugging-with-browser">Debugging with <code>browser()</code></a></li>
  </ul></li>
  <li><a href="#where-this-script-goes-next" id="toc-where-this-script-goes-next" class="nav-link" data-scroll-target="#where-this-script-goes-next"><span class="header-section-number">4.5</span> Where this script goes next</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li>Links</li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/njtierney/rbestpractices/edit/main/writing-functions.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/njtierney/rbestpractices/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-writing-functions" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Writing functions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>“You should consider writing a function whenever you’ve copied and pasted a block of code more than twice.”</p>
<p>– Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund, <a href="https://r4ds.hadley.nz/functions.html">R for Data Science</a></p>
</blockquote>
<p>At some point you notice you have written this, or something like it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-label="1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-label="2"></a>adelie_mean <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-label="3"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">"Adelie"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-label="4"></a>  <span class="fu">pull</span>(body_mass) <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-label="5"></a>  <span class="fu">mean</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-label="6"></a>gentoo_mean <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-label="7"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">"Gentoo"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-label="8"></a>  <span class="fu">pull</span>(body_mass) <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-label="9"></a>  <span class="fu">mean</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-label="10"></a>chinstrap_mean <span class="ot">&lt;-</span> penguins <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-label="11"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">"Chinstrap"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-label="12"></a>  <span class="fu">pull</span>(body_mass) <span class="sc">|&gt;</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-label="13"></a>  <span class="fu">mean</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The same line three times, with one word changed. That is a function waiting to happen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-label="1"></a>species_body_mass_mean <span class="ot">&lt;-</span> <span class="cf">function</span>(species_name){</span>
<span id="cb2-2"><a href="#cb2-2" aria-label="2"></a>  penguins <span class="sc">|&gt;</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-label="3"></a>    <span class="fu">filter</span>(species <span class="sc">==</span> species_name) <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-label="4"></a>    <span class="fu">pull</span>(body_mass) <span class="sc">|&gt;</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-label="5"></a>    <span class="fu">mean</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-label="6"></a>}</span>
<span id="cb2-7"><a href="#cb2-7" aria-label="7"></a>adelie_mean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3700.662</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-label="1"></a><span class="fu">species_body_mass_mean</span>(<span class="st">"Adelie"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3700.662</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-label="1"></a>gentoo_mean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5076.016</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-label="1"></a><span class="fu">species_body_mass_mean</span>(<span class="st">"Gentoo"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5076.016</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-label="1"></a>chinstrap_mean</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3733.088</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-label="1"></a><span class="fu">species_body_mass_mean</span>(<span class="st">"Chinstrap"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3733.088</code></pre>
</div>
</div>
<p>This section is about noticing that moment, and knowing what to do about it. We look at the problem functions solve, what a good small function looks like, and how to get inside one when it misbehaves.</p>
<section id="overview" class="level2 unnumbered overview">
<h2 class="unnumbered anchored" data-anchor-id="overview">Overview</h2>
<p><strong>Duration</strong> 60 minutes</p>
<p><strong>Questions</strong></p>
<ul>
<li>What problem do functions actually solve?</li>
<li>What are the parts of a function called, and why does that matter?</li>
<li>What should I call a function, and what should I call its arguments?</li>
<li>How do I look inside a function when it goes wrong?</li>
</ul>
</section>
<section id="the-problem-functions-solve" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-problem-functions-solve"><span class="header-section-number">4.1</span> The problem functions solve</h2>
<p>I do not think I can overstate this: learning to write functions changed how I think about code, and how I think about solving problems. It takes time to develop, and the payoff is enormous.</p>
<p>A function isn’t only a way to avoid typing something twice. It’s a way to take an idea, give it a name, and then think in terms of that name rather than the twenty lines underneath it.</p>
<p>Once you can do that, you can hold a bigger problem in your head. That is why I would call functions a thinking tool rather than a typing tool.</p>
<p>Let me tell you how I got there, because I got there slowly.</p>
<p>In 2013 I was writing code to calculate a t-test from scratch. At the top of my script was something like:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-label="1"></a>var_1 <span class="ot">&lt;-</span> data<span class="sc">$</span>x1</span>
<span id="cb14-2"><a href="#cb14-2" aria-label="2"></a>var_2 <span class="ot">&lt;-</span> data<span class="sc">$</span>x2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>and then a pile of code that computed the result.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="The whole script, if you want to see it">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The whole script, if you want to see it
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This is roughly what the rest of it looked like. You do not need to read it closely. The thing I want you to notice is how much of it there is, and where the two lines I kept editing are.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="annotated-cell-39"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-39" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-39-1" class="code-annotation-target"><a href="#annotated-cell-39-1" aria-label="1"></a>var_1 <span class="ot">&lt;-</span> data<span class="sc">$</span>x1</span>
<span id="annotated-cell-39-2"><a href="#annotated-cell-39-2" aria-label="2"></a>var_2 <span class="ot">&lt;-</span> data<span class="sc">$</span>x2</span>
<span id="annotated-cell-39-3"><a href="#annotated-cell-39-3" aria-label="3"></a></span>
<span id="annotated-cell-39-4"><a href="#annotated-cell-39-4" aria-label="4"></a>n_1 <span class="ot">&lt;-</span> <span class="fu">length</span>(var_1)</span>
<span id="annotated-cell-39-5"><a href="#annotated-cell-39-5" aria-label="5"></a>n_2 <span class="ot">&lt;-</span> <span class="fu">length</span>(var_2)</span>
<span id="annotated-cell-39-6"><a href="#annotated-cell-39-6" aria-label="6"></a></span>
<span id="annotated-cell-39-7"><a href="#annotated-cell-39-7" aria-label="7"></a>mean_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(var_1)</span>
<span id="annotated-cell-39-8"><a href="#annotated-cell-39-8" aria-label="8"></a>mean_2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(var_2)</span>
<span id="annotated-cell-39-9"><a href="#annotated-cell-39-9" aria-label="9"></a></span>
<span id="annotated-cell-39-10"><a href="#annotated-cell-39-10" aria-label="10"></a>var_within_1 <span class="ot">&lt;-</span> <span class="fu">sum</span>((var_1 <span class="sc">-</span> mean_1)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n_1 <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="annotated-cell-39-11"><a href="#annotated-cell-39-11" aria-label="11"></a>var_within_2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((var_2 <span class="sc">-</span> mean_2)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n_2 <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="annotated-cell-39-12"><a href="#annotated-cell-39-12" aria-label="12"></a></span>
<span id="annotated-cell-39-13"><a href="#annotated-cell-39-13" aria-label="13"></a>pooled_var <span class="ot">&lt;-</span> ((n_1 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> var_within_1 <span class="sc">+</span> (n_2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> var_within_2) <span class="sc">/</span> (n_1 <span class="sc">+</span> n_2 <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="annotated-cell-39-14"><a href="#annotated-cell-39-14" aria-label="14"></a>std_error <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(pooled_var <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">/</span> n_1 <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> n_2))</span>
<span id="annotated-cell-39-15"><a href="#annotated-cell-39-15" aria-label="15"></a></span>
<span id="annotated-cell-39-16"><a href="#annotated-cell-39-16" aria-label="16"></a>t_statistic <span class="ot">&lt;-</span> (mean_1 <span class="sc">-</span> mean_2) <span class="sc">/</span> std_error</span>
<span id="annotated-cell-39-17"><a href="#annotated-cell-39-17" aria-label="17"></a>degrees_freedom <span class="ot">&lt;-</span> n_1 <span class="sc">+</span> n_2 <span class="sc">-</span> <span class="dv">2</span></span>
<span id="annotated-cell-39-18"><a href="#annotated-cell-39-18" aria-label="18"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t_statistic), <span class="at">df =</span> degrees_freedom)</span>
<span id="annotated-cell-39-19"><a href="#annotated-cell-39-19" aria-label="19"></a></span>
<span id="annotated-cell-39-20"><a href="#annotated-cell-39-20" aria-label="20"></a>t_statistic</span>
<span id="annotated-cell-39-21"><a href="#annotated-cell-39-21" aria-label="21"></a>p_value</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-39" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-39" data-code-lines="1,2" data-code-annotation="1">These two lines are the only part that ever changed.</span>
</dd>
</dl>
</div>
</div>
</div>
<p>Every time I wanted to look at a different pair of variables, I went back to the top, changed those two lines, and ran the whole script again.</p>
<p>Two lines out of twenty. The other eighteen never changed, and I re-ran all of them, by hand, every single time.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/two-lines-of-twenty.png" class="img-fluid figure-img" style="width:100.0%" alt="Four copies of the same script side by side, drawn as rows of grey bars rather than readable code. In every copy the top two rows are coloured, a different colour in each copy, and the remaining eighteen rows are identical grey. A label underneath reads: two lines changed, the other eighteen ran again anyway, every single time."></p>
<figcaption>Four runs of the same script. Two bars change colour.</figcaption>
</figure>
</div>
<p>Here is what I actually wanted, and could not yet write:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-label="1"></a><span class="fu">t_test</span>(<span class="at">var_1 =</span> data<span class="sc">$</span>x1, <span class="at">var_2 =</span> data<span class="sc">$</span>x2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One line. The eighteen that never changed go inside it, once, and stop being something I have to look at. The two that do change become arguments, which is the whole job of an argument.</p>
<p>Something about this felt wrong at the time. But I didn’t have the words for it.</p>
<p>What I was reaching for sounded something like:</p>
<blockquote class="blockquote">
<p>I want to run this script, but get the top couple of lines to change depending on which variables I specify.</p>
</blockquote>
<p>What I needed was a function. I just didn’t know it.</p>
<p>I had been <strong>taught</strong> functions by then. And I had been <strong>using</strong> functions the whole time, things like <code>lm()</code>, <code>table()</code>, <code>subset()</code>, and <code>read.csv()</code>. I used them every day without ever thinking about where they came from, or that I could make my own.</p>
<p>But the examples I was taught with were “convert Celsius to Fahrenheit” and “identify odd numbers”, and I couldn’t see how those applied to anything I actually did.</p>
<p>They seemed like useful kitchen trinkets. An apple corer, a garlic press. Rather than a fundamental skill, like knowing how to use a knife.</p>
<p>Functions are the knife.</p>
<p>So rather than argue that, let me show you.</p>
<p>What does this code do?</p>
<p>We’ll use <code>penguins</code>, which comes with R.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-label="1"></a><span class="fu">head</span>(penguins)</span>
<span id="cb16-2"><a href="#cb16-2" aria-label="2"></a><span class="co">#&gt;   species    island bill_len bill_dep flipper_len body_mass    sex year</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-label="3"></a><span class="co">#&gt; 1  Adelie Torgersen     39.1     18.7         181      3750   male 2007</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-label="4"></a><span class="co">#&gt; 2  Adelie Torgersen     39.5     17.4         186      3800 female 2007</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-label="5"></a><span class="co">#&gt; 3  Adelie Torgersen     40.3     18.0         195      3250 female 2007</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-label="6"></a><span class="co">#&gt; 4  Adelie Torgersen       NA       NA          NA        NA   &lt;NA&gt; 2007</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-label="7"></a><span class="co">#&gt; 5  Adelie Torgersen     36.7     19.3         193      3450 female 2007</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-label="8"></a><span class="co">#&gt; 6  Adelie Torgersen     39.3     20.6         190      3650   male 2007</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-label="1"></a>bill_len <span class="ot">&lt;-</span> penguins<span class="sc">$</span>bill_len</span>
<span id="cb17-2"><a href="#cb17-2" aria-label="2"></a>bill_dep <span class="ot">&lt;-</span> penguins<span class="sc">$</span>bill_dep</span>
<span id="cb17-3"><a href="#cb17-3" aria-label="3"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-label="4"></a>bill_len_0 <span class="ot">&lt;-</span> (bill_len <span class="sc">-</span> <span class="fu">mean</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-label="5"></a>bill_dep_0 <span class="ot">&lt;-</span> (bill_dep <span class="sc">-</span> <span class="fu">mean</span>(bill_dep, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Before you read on, have a proper go at this one.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Your Turn">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here is the code again. Don’t run it.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-label="1"></a>bill_len <span class="ot">&lt;-</span> penguins<span class="sc">$</span>bill_len</span>
<span id="cb18-2"><a href="#cb18-2" aria-label="2"></a>bill_dep <span class="ot">&lt;-</span> penguins<span class="sc">$</span>bill_dep</span>
<span id="cb18-3"><a href="#cb18-3" aria-label="3"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-label="4"></a>bill_len_0 <span class="ot">&lt;-</span> (bill_len <span class="sc">-</span> <span class="fu">mean</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-label="5"></a>bill_dep_0 <span class="ot">&lt;-</span> (bill_dep <span class="sc">-</span> <span class="fu">mean</span>(bill_dep, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ol type="1">
<li>In one sentence, what is this code doing?</li>
<li>There is a bug in it. Find it.</li>
<li>How long did that take you, and what made it hard?</li>
</ol>
</div>
</div>
<p>So, what is it doing?</p>
<p>This is mean centering and scaling. It’s a transformation that gives your data a mean of 0 and a standard deviation of 1, which some statistical models want.</p>
<p>But reading that code, it’s hard to see that’s what’s happening. Nothing in it says “centre and scale”. You have to reconstruct the intent from the arithmetic.</p>
<p>Worse, it invites errors, because you have to repeat <code>bill_len</code> or <code>bill_dep</code> three times per line.</p>
<p>And there <strong>is</strong> an error.</p>
<p>Look at the second line again. For <code>bill_dep_0</code>, I divide by the standard deviation of <strong><code>bill_len</code></strong>, not <code>bill_dep</code>.</p>
<p>That’s a copy-paste bug, it’s completely silent, and it produces numbers that look entirely plausible. If you found it, well done. If you didn’t, that is exactly what worries me, and it is why I would rather not rely on either of us spotting it.</p>
<p>A function fixes this by <strong>abstracting away</strong> the need to write the variable in each time. Break it into two steps:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-label="1"></a>mean_center <span class="ot">&lt;-</span> <span class="cf">function</span>(variable) {</span>
<span id="cb19-2"><a href="#cb19-2" aria-label="2"></a>  variable <span class="sc">-</span> <span class="fu">mean</span>(variable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-label="3"></a>}</span>
<span id="cb19-4"><a href="#cb19-4" aria-label="4"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-label="5"></a>scale_sd <span class="ot">&lt;-</span> <span class="cf">function</span>(variable) {</span>
<span id="cb19-6"><a href="#cb19-6" aria-label="6"></a>  variable <span class="sc">/</span> <span class="fu">sd</span>(variable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-label="7"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Now we can write:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-label="1"></a>bill_len <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-label="2"></a>  <span class="fu">mean_center</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-label="3"></a>  <span class="fu">scale_sd</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Or write one function that does both steps:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-label="1"></a>center_scale <span class="ot">&lt;-</span> <span class="cf">function</span>(variable) {</span>
<span id="cb21-2"><a href="#cb21-2" aria-label="2"></a>  centered <span class="ot">&lt;-</span> <span class="fu">mean_center</span>(variable)</span>
<span id="cb21-3"><a href="#cb21-3" aria-label="3"></a>  centered_scaled <span class="ot">&lt;-</span> <span class="fu">scale_sd</span>(centered)</span>
<span id="cb21-4"><a href="#cb21-4" aria-label="4"></a>  centered_scaled</span>
<span id="cb21-5"><a href="#cb21-5" aria-label="5"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>What is nice here is that each function <strong>describes what it does</strong> in its name. Reading <code>center_scale</code>, you can see it does a thing called <code>mean_center</code> first, then <code>scale_sd</code> next.</p>
<p>So compare the original:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-label="1"></a>bill_len_0 <span class="ot">&lt;-</span> (bill_len <span class="sc">-</span> <span class="fu">mean</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-label="2"></a>bill_dep_0 <span class="ot">&lt;-</span> (bill_dep <span class="sc">-</span> <span class="fu">mean</span>(bill_dep, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="fu">sd</span>(bill_len, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>with:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-label="1"></a>bill_len_0 <span class="ot">&lt;-</span> <span class="fu">center_scale</span>(bill_len)</span>
<span id="cb23-2"><a href="#cb23-2" aria-label="2"></a>bill_dep_0 <span class="ot">&lt;-</span> <span class="fu">center_scale</span>(bill_dep)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The bug I planted above isn’t just fixed in the second version. It’s become almost impossible to write.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Someone has probably done this already">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Someone has probably done this already
</div>
</div>
<div class="callout-body-container callout-body">
<p>Base R has <code>scale()</code>. Its help page describes it as centring and scaling the columns of a numeric matrix, which is the two steps we just wrote, in one call.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-label="1"></a><span class="fu">head</span>(<span class="fu">center_scale</span>(bill_len), <span class="dv">3</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-label="2"></a><span class="co">#&gt; [1] -0.8832047 -0.8099390 -0.6634077</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-label="3"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-label="4"></a><span class="fu">head</span>(<span class="fu">scale</span>(bill_len), <span class="dv">3</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-label="5"></a><span class="co">#&gt;            [,1]</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-label="6"></a><span class="co">#&gt; [1,] -0.8832047</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-label="7"></a><span class="co">#&gt; [2,] -0.8099390</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-label="8"></a><span class="co">#&gt; [3,] -0.6634077</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Same numbers. The only difference is that <code>scale()</code> hands back a matrix, because it is built to do every column of one at a time.</p>
<p>Which is a good argument for checking whether a solution exists before writing your own. You don’t need to write everything from scratch.</p>
<p>At worst you find nobody has solved your problem, which is an opportunity. Usually you learn the words other people use to describe it, which makes your next search much better.</p>
</div>
</div>
</section>
<section id="anatomy-of-a-function" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="anatomy-of-a-function"><span class="header-section-number">4.2</span> Anatomy of a function</h2>
<p>Every function in R has the same few parts. Once you can point at them, functions stop looking like magic.</p>
<p>The reason to learn the names is practical. When you know a thing is called a “default argument”, you can search for it, read the help page about it, and ask someone a question that gets you a useful answer. Without the words, you are stuck describing the shape of the problem and hoping.</p>
<p>We’ll use two small functions here. The first counts how many values are missing:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-label="1"></a>n_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-label="2"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(x))</span>
<span id="cb25-3"><a href="#cb25-3" aria-label="3"></a>}</span>
<span id="cb25-4"><a href="#cb25-4" aria-label="4"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-label="5"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Ozone)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37</code></pre>
</div>
</div>
<p>The second uses that one to work out what <strong>proportion</strong> is missing, which is usually the first thing I want to know about a dataset I have been handed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-label="1"></a>prop_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">2</span>) {</span>
<span id="cb27-2"><a href="#cb27-2" aria-label="2"></a>  prop <span class="ot">&lt;-</span> <span class="fu">n_missing</span>(x) <span class="sc">/</span> <span class="fu">length</span>(x)</span>
<span id="cb27-3"><a href="#cb27-3" aria-label="3"></a>  <span class="fu">round</span>(prop, digits)</span>
<span id="cb27-4"><a href="#cb27-4" aria-label="4"></a>}</span>
<span id="cb27-5"><a href="#cb27-5" aria-label="5"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-label="6"></a><span class="fu">prop_missing</span>(airquality<span class="sc">$</span>Ozone)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.24</code></pre>
</div>
</div>
<p>Notice that <code>prop_missing()</code> calls <code>n_missing()</code>. That is worth pointing at, because it is how most real code gets built. You write a small function that does one thing, and then you use it inside the next one, instead of writing <code>sum(is.na(x))</code> again and hoping you type it the same way.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/function-anatomy.png" class="img-fluid figure-img" style="width:100.0%" alt="The function prop_missing defined with function(x, digits = 2), with six parts highlighted in colour: the name, the function keyword, the argument x, the default digits = 2, the body, and the return value."></p>
<figcaption>The parts of a function.</figcaption>
</figure>
</div>
<p>Taking the parts one at a time:</p>
<ul>
<li><strong>The name.</strong> <code>prop_missing</code>. This is how you call it later, so it is worth the two minutes it takes to pick a good one. There is more on that just below.</li>
<li><strong><code>function()</code>.</strong> This is the bit that actually creates a function. <code>prop_missing &lt;-</code> just binds it to a name, the same way you would bind any other value.</li>
<li><strong>The arguments.</strong> <code>x</code> and <code>digits</code>. These are the things that change each time you call it. They are the answer to “what did I keep editing at the top of my script?”</li>
<li><strong>A default.</strong> <code>digits = 2</code>. If the caller doesn’t supply <code>digits</code>, it is 2. Defaults let you make a function easy to call in the common case, without giving up control in the uncommon one.</li>
<li><strong>The body.</strong> Everything between the braces. This is the code that runs.</li>
<li><strong>The return value.</strong> R returns the <strong>last thing evaluated</strong>, so here that’s the rounded proportion. You can write <code>return()</code> explicitly, and sometimes should for an early exit, but you don’t have to.</li>
</ul>
<section id="naming-a-function" class="level3">
<h3 class="anchored" data-anchor-id="naming-a-function">Naming a function</h3>
<p>We spent a whole chapter on naming variables, and functions get the same treatment. The difference is that a function <strong>does</strong> something, so the name should say what.</p>
<p>Watch this one improve:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-label="1"></a><span class="fu">myfun</span>()                    <span class="co"># what?</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-label="2"></a><span class="fu">temperature_conversion</span>()   <span class="co"># better, but converting what to what?</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-label="3"></a><span class="fu">celcius_to_fahrenheit</span>()    <span class="co"># now I don't have to read the body</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The pattern that gets you there is <strong><code>input_to_output()</code></strong>. Not every function fits it, but reaching for it is a fast way to find out whether you actually know what your function does. If you can’t fill in both halves, that is worth knowing before you write the body.</p>
<p>The same care goes inside. Name the arguments and the intermediate values to match:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-label="1"></a>celcius_to_fahrenheit <span class="ot">&lt;-</span> <span class="cf">function</span>(celcius) {</span>
<span id="cb30-2"><a href="#cb30-2" aria-label="2"></a>  fahrenheit <span class="ot">&lt;-</span> (celcius <span class="sc">*</span> <span class="dv">9</span> <span class="sc">/</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="dv">32</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-label="3"></a>  fahrenheit</span>
<span id="cb30-4"><a href="#cb30-4" aria-label="4"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Read that and there is nothing left to work out. The argument says what goes in, the intermediate says what comes out, and the name says what happened in between.</p>
</section>
<section id="arguments-and-where-their-values-come-from" class="level3">
<h3 class="anchored" data-anchor-id="arguments-and-where-their-values-come-from">Arguments, and where their values come from</h3>
<p>The arguments are the part that trips people up, because <code>x</code> and <code>digits</code> do not have values when you write the definition. They are names waiting for something. The values arrive when you call the function, and where they arrive is decided by the order you write them in:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/function-in-use.png" class="img-fluid figure-img" style="width:100.0%" alt="Three panels. The first shows the definition prop_missing <- function(x, digits = 2), with x highlighted in orange and digits = 2 in brown. The second shows the call prop_missing(airquality$Ozone), with airquality$Ozone underlined in orange and labelled 'becomes x', a badge noting that digits falls back to 2, and the result 0.24. The third shows prop_missing(airquality$Ozone, digits = 4), with airquality$Ozone labelled 'becomes x' and digits = 4 labelled 'becomes digits', returning 0.2418."></p>
<figcaption>Argument values arrive at the call, not at the definition.</figcaption>
</figure>
</div>
<p>The same function, two different answers, and nothing about the function changed. That is the whole job of an argument.</p>
<p>You can hand the values over in two ways. <strong>By position</strong>, in the order the definition lists them, or <strong>by name</strong>, using <code>name = value</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/argument-order.png" class="img-fluid figure-img" style="width:100.0%" alt="A function definition, prop_missing with arguments x and digits equals two, shown at the top along with ozone being assigned from airquality dollar Ozone. Below it three calls, all returning the same answer. The first passes both values by position and is marked by position, with the note that you have to know the definition to read it. The second names both arguments and is marked by name, the habit worth having. The third names both but puts them in the opposite order, and is marked by name any order, because naming makes order irrelevant."></p>
<figcaption>Naming them costs a few keystrokes and buys you a line that reads on its own.</figcaption>
</figure>
</div>
<p>All three give the same answer. The difference is what you have to already know in order to read the line.</p>
<p><strong>Name your arguments where you can.</strong> <code>prop_missing(ozone, 4)</code> requires you to remember what the second slot is for. <code>prop_missing(x = ozone, digits = 4)</code> tells you. The first argument is usually obvious enough to leave positional, and everything after it is worth naming.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Your Turn">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here is a function. Don’t run it, and don’t worry about what it computes.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-label="1"></a>rate_per_1000 <span class="ot">&lt;-</span> <span class="cf">function</span>(count, population, <span class="at">digits =</span> <span class="dv">1</span>) {</span>
<span id="cb31-2"><a href="#cb31-2" aria-label="2"></a>  rate <span class="ot">&lt;-</span> (count <span class="sc">/</span> population) <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-label="3"></a>  <span class="fu">round</span>(rate, digits)</span>
<span id="cb31-4"><a href="#cb31-4" aria-label="4"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Name the parts:</p>
<ol type="1">
<li>What is the <strong>name</strong> of this function?</li>
<li>What are its <strong>arguments</strong>?</li>
<li>Which argument has a <strong>default</strong>, and what is it?</li>
<li>What is the <strong>body</strong>?</li>
<li>What does it <strong>return</strong>?</li>
<li>Now call it two ways: once letting <code>digits</code> take its default, and once setting it yourself.</li>
</ol>
<p>This one is really about the vocabulary. Once you can say “the third argument has a default”, you can look it up and you can ask about it.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Two more parts, once the above is comfortable">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Two more parts, once the above is comfortable
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>These are worth knowing about eventually. Skip them for now if you are still getting the hang of the parts above.</p>
<p><strong>Side effects.</strong> Anything a function does <strong>other</strong> than return a value. Printing to the console, writing a file, drawing a plot, setting an option. Side effects are not bad, and plenty of useful functions have them. But a function that both returns something useful <strong>and</strong> quietly writes a file is harder to reason about than one that does a single one of those things.</p>
<p><strong>Functions are values.</strong> An argument can be a function. Here is the situation where you would want that.</p>
<p>Say you want to know how many values are missing in each column of your data. With the function we already have, you could write:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-label="1"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb32-2"><a href="#cb32-2" aria-label="2"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Solar.R)</span>
<span id="cb32-3"><a href="#cb32-3" aria-label="3"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Wind)</span>
<span id="cb32-4"><a href="#cb32-4" aria-label="4"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Temp)</span>
<span id="cb32-5"><a href="#cb32-5" aria-label="5"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Month)</span>
<span id="cb32-6"><a href="#cb32-6" aria-label="6"></a><span class="fu">n_missing</span>(airquality<span class="sc">$</span>Day)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>That is six lines to say one thing. You have to know every column name, you have to type each one correctly, and when the data gains a column next month you have to remember to come back and add a line.</p>
<p>It is the copy-paste problem from the start of this chapter, wearing a different hat.</p>
<p>What you want to say is “do this to every column”. To say that, you need to hand one function to another function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-label="1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb33-2"><a href="#cb33-2" aria-label="2"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-label="3"></a><span class="fu">map_int</span>(airquality, n_missing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Ozone Solar.R    Wind    Temp   Month     Day 
     37       7       0       0       0       0 </code></pre>
</div>
</div>
<p>One line, and it does not care how many columns there are or what they are called.</p>
<p>Look closely at how <code>n_missing</code> is written there. <strong>No brackets.</strong> We are not calling it, we are handing it over, the same way we would hand over a number or a data frame. That is what “functions are values” means.</p>
<p>And you can accept a function in your own functions too:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-label="1"></a>n_complete <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb35-2"><a href="#cb35-2" aria-label="2"></a>  <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x))</span>
<span id="cb35-3"><a href="#cb35-3" aria-label="3"></a>}</span>
<span id="cb35-4"><a href="#cb35-4" aria-label="4"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-label="5"></a>summarise_columns <span class="ot">&lt;-</span> <span class="cf">function</span>(data, f) {</span>
<span id="cb35-6"><a href="#cb35-6" aria-label="6"></a>  <span class="fu">map_dbl</span>(data, f)</span>
<span id="cb35-7"><a href="#cb35-7" aria-label="7"></a>}</span>
<span id="cb35-8"><a href="#cb35-8" aria-label="8"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-label="9"></a><span class="fu">summarise_columns</span>(airquality, n_complete)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Ozone Solar.R    Wind    Temp   Month     Day 
    116     146     153     153     153     153 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="A quick word on `map()`">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>A quick word on <code>map()</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://purrr.tidyverse.org/"><code>purrr</code></a> is the tidyverse package for applying a function to each element of something. The suffix tells you what comes back: <code>map()</code> gives a <strong>list</strong>, <code>map_int()</code> an <strong>integer vector</strong>, <code>map_dbl()</code> a <strong>double vector</strong>, and so on.</p>
<p>The typed ones error if the function cannot deliver that shape, which is the useful half. You say what you are expecting, and you find out straight away rather than three lines later.</p>
<p>Base R has its own versions, called <code>lapply()</code>, <code>vapply()</code> and <code>sapply()</code>.</p>
<p>Handing over a function you will only use once, without naming it, is worth knowing about too. That is in <a href="appendix-anonymous-functions.html" class="quarto-xref">Anonymous functions&nbsp;<span>B</span></a>.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="other-things-worth-turning-into-a-function" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="other-things-worth-turning-into-a-function"><span class="header-section-number">4.3</span> Other things worth turning into a function</h2>
<p>Centering and scaling is one kind of job. Here are a few others, so the idea doesn’t get stuck to that one example.</p>
<p><strong>A calculation you keep redoing.</strong> Body mass index, a rate per thousand, a unit conversion.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-label="1"></a>bmi <span class="ot">&lt;-</span> <span class="cf">function</span>(weight_kg, height_m) {</span>
<span id="cb37-2"><a href="#cb37-2" aria-label="2"></a>  weight_kg <span class="sc">/</span> height_m<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-label="3"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Read that definition and you can check the units are right without knowing the formula. The argument names do it for you.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-label="1"></a><span class="fu">bmi</span>(<span class="at">weight_kg =</span> <span class="dv">70</span>, <span class="at">height_m =</span> <span class="fl">1.75</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-label="2"></a><span class="co">#&gt; [1] 22.85714</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Unit conversions are the same idea, and they are the most boring functions in the world. I write them constantly.</p>
<p><code>penguins</code> records body mass in grams, and I think about penguins in kilograms:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-label="1"></a>grams_to_kg <span class="ot">&lt;-</span> <span class="cf">function</span>(grams) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-label="2"></a>  grams <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-label="3"></a>}</span>
<span id="cb39-4"><a href="#cb39-4" aria-label="4"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-label="5"></a>penguins<span class="sc">$</span>body_mass_kg <span class="ot">&lt;-</span> <span class="fu">grams_to_kg</span>(penguins<span class="sc">$</span>body_mass)</span>
<span id="cb39-6"><a href="#cb39-6" aria-label="6"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-label="7"></a><span class="fu">head</span>(penguins[<span class="fu">c</span>(<span class="st">"species"</span>, <span class="st">"body_mass"</span>, <span class="st">"body_mass_kg"</span>)], <span class="dv">4</span>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-label="8"></a><span class="co">#&gt;   species body_mass body_mass_kg</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-label="9"></a><span class="co">#&gt; 1  Adelie      3750         3.75</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-label="10"></a><span class="co">#&gt; 2  Adelie      3800         3.80</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-label="11"></a><span class="co">#&gt; 3  Adelie      3250         3.25</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-label="12"></a><span class="co">#&gt; 4  Adelie        NA           NA</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One line, and it is obvious what it does. Written inline as <code>penguins$body_mass / 1000</code> it is a magic number you have to decode every time you meet it.</p>
<p><strong>A check you want to run on every dataset that comes in.</strong> We built one of these a moment ago: <code>n_missing()</code>, in <a href="#anatomy-of-a-function">Anatomy of a function</a>.</p>
<p>None of these are clever. That is deliberate. It’s OK if the function is three lines long and doing something boring. Most of mine are, and they are still what makes the analysis readable.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Small functions add up">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Small functions add up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Here is one more of the same kind, to go with the two we already have:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-label="1"></a>n_complete <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb40-2"><a href="#cb40-2" aria-label="2"></a>  <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x))</span>
<span id="cb40-3"><a href="#cb40-3" aria-label="3"></a>}</span>
<span id="cb40-4"><a href="#cb40-4" aria-label="4"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-label="5"></a><span class="fu">n_complete</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb40-6"><a href="#cb40-6" aria-label="6"></a><span class="co">#&gt; [1] 116</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Three things to notice across the set of them.</p>
<p><code>prop_missing()</code> <strong>calls</strong> <code>n_missing()</code> rather than writing <code>sum(is.na(x))</code> out a second time. Fix one and you have fixed both.</p>
<p>They are <strong>named for the question they answer</strong>, not for how they answer it. <code>prop_missing()</code>, not <code>round_na_ratio()</code>.</p>
<p><code>prop_missing()</code> takes a <strong>default</strong> for the one thing people argue about, so the common call stays short and you can still override it.</p>
<p>We come back to <code>prop_missing()</code> in the very next section, when we put a bug in it and go looking with a debugger.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Your Turn">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Look at your most recent analysis script.</p>
<ol type="1">
<li>Find a chunk of code you have written more than once, with something small changed each time.</li>
<li>Write down, in one sentence, what that chunk is <strong>for</strong>.</li>
<li>That sentence is the name of a function you haven’t written yet. Don’t write it yet, just note it down.</li>
</ol>
</div>
</div>
</section>
<section id="how-to-use-a-debugger" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="how-to-use-a-debugger"><span class="header-section-number">4.4</span> How to use a debugger</h2>
<p>R is interactive. You run some code, you see the output immediately, and when something goes wrong you can poke around and look at it. It is a lovely way to do data analysis.</p>
<p>Functions break that. A function is a box, and by default you can’t see inside it while it runs.</p>
<p>Here is what I mean. Give <code>prop_missing()</code> an intermediate value on its way to the answer:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-label="1"></a>prop_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">2</span>) {</span>
<span id="cb41-2"><a href="#cb41-2" aria-label="2"></a>  prop <span class="ot">&lt;-</span> <span class="fu">n_missing</span>(x) <span class="sc">/</span> <span class="fu">length</span>(x)</span>
<span id="cb41-3"><a href="#cb41-3" aria-label="3"></a>  <span class="fu">round</span>(prop, digits)</span>
<span id="cb41-4"><a href="#cb41-4" aria-label="4"></a>}</span>
<span id="cb41-5"><a href="#cb41-5" aria-label="5"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-label="6"></a><span class="fu">prop_missing</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb41-7"><a href="#cb41-7" aria-label="7"></a><span class="co">#&gt; [1] 0.24</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Now go and have a look at <code>prop</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-label="1"></a>prop</span>
<span id="cb42-2"><a href="#cb42-2" aria-label="2"></a><span class="co">#&gt; Error: object 'prop' not found</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>It existed. The function could not have given you an answer without it. But it lived inside the box, for a moment, and there is no way to reach it from out here.</p>
<p>Every debugging trick you already know stops working. You can’t print it, you can’t <code>View()</code> it, you can’t check its class.</p>
<p>To look inside, you need a debugger.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="A confession">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>A confession
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you have ever copied the internals of a function into a new script, hard-coded the arguments at the top, and run it line by line - this section is for you.</p>
<p>I say that as someone who did exactly that for years.</p>
</div>
</div>
<section id="a-good-case-for-a-debugger" class="level3">
<h3 class="anchored" data-anchor-id="a-good-case-for-a-debugger">A good case for a debugger</h3>
<p>Small functions do not need one. <code>mean_center()</code> is two lines, and you can read it.</p>
<p>It gets harder the moment functions call other functions. Here is <code>prop_missing()</code> from earlier in the chapter:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-label="1"></a>n_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb43-2"><a href="#cb43-2" aria-label="2"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(x))</span>
<span id="cb43-3"><a href="#cb43-3" aria-label="3"></a>}</span>
<span id="cb43-4"><a href="#cb43-4" aria-label="4"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-label="5"></a>prop_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">2</span>) {</span>
<span id="cb43-6"><a href="#cb43-6" aria-label="6"></a>  <span class="fu">round</span>(<span class="fu">n_missing</span>(x) <span class="sc">/</span> <span class="fu">length</span>(x), digits)</span>
<span id="cb43-7"><a href="#cb43-7" aria-label="7"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>When <code>prop_missing()</code> gives you a number you don’t believe, the problem could be in either function, and <code>x</code> inside <code>n_missing()</code> is not an object you can look at. It exists for a moment, in the middle of a call you did not make directly, and then it is gone.</p>
<p>Later in this chapter we take a hundred line script apart, and end up with functions that have the same problem three levels deep instead of two:</p>
<pre><code>read_educated_population()
└── prepare_education()
    └── extract_rows_set_names()</code></pre>
<p><code>extract_rows_set_names()</code> is where the slicing happens, and it is also called <strong>twice</strong>, once for the education rows and once for the population rows, with different arguments each time. When something comes out wrong, you cannot see which call did it.</p>
<p>That is what a debugger is for.</p>
</section>
<section id="debugging-with-browser" class="level3">
<h3 class="anchored" data-anchor-id="debugging-with-browser">Debugging with <code>browser()</code></h3>
<p>Let’s give ourselves something to find. Here is <code>prop_missing()</code> again, with one small change:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-label="1"></a>n_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb45-2"><a href="#cb45-2" aria-label="2"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(x))</span>
<span id="cb45-3"><a href="#cb45-3" aria-label="3"></a>}</span>
<span id="cb45-4"><a href="#cb45-4" aria-label="4"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-label="5"></a>prop_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">2</span>) {</span>
<span id="cb45-6"><a href="#cb45-6" aria-label="6"></a>  <span class="fu">round</span>(<span class="fu">n_missing</span>(x) <span class="sc">/</span> <span class="fu">length</span>(<span class="fu">na.omit</span>(x)), digits)</span>
<span id="cb45-7"><a href="#cb45-7" aria-label="7"></a>}</span>
<span id="cb45-8"><a href="#cb45-8" aria-label="8"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-label="9"></a><span class="fu">prop_missing</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb45-10"><a href="#cb45-10" aria-label="10"></a><span class="co">#&gt; [1] 0.32</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>It runs. Nothing errors, nothing warns, and <code>0.32</code> is a perfectly believable proportion of missing values.</p>
<p>It’s also wrong. Earlier in the chapter, that same column gave us <code>0.24</code>.</p>
<p>So which of the two functions is lying? Nothing on screen tells you, and neither one is long enough to be obviously at fault. Let’s go and look.</p>
<p><strong><code>browser()</code> is a stop sign you put inside a function.</strong> Write it on the line you want to stop at:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-label="1"></a>prop_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">2</span>) {</span>
<span id="cb46-2"><a href="#cb46-2" aria-label="2"></a>  <span class="fu">browser</span>()</span>
<span id="cb46-3"><a href="#cb46-3" aria-label="3"></a>  <span class="fu">round</span>(<span class="fu">n_missing</span>(x) <span class="sc">/</span> <span class="fu">length</span>(<span class="fu">na.omit</span>(x)), digits)</span>
<span id="cb46-4"><a href="#cb46-4" aria-label="4"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Now call the function the way you normally would:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-label="1"></a><span class="fu">prop_missing</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb47-2"><a href="#cb47-2" aria-label="2"></a><span class="co">#&gt; Called from: prop_missing(airquality$Ozone)</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-label="3"></a><span class="co">#&gt; Browse[1]&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>That <code>Browse[1]&gt;</code> is an R console, and it is standing <strong>inside</strong> the function. Every argument is now a real object you can look at, so look at the two numbers going into the division:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-label="1"></a>Browse[<span class="dv">1</span>]<span class="sc">&gt;</span> <span class="fu">length</span>(x)</span>
<span id="cb48-2"><a href="#cb48-2" aria-label="2"></a><span class="co">#&gt; [1] 153</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-label="3"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-label="4"></a>Browse[<span class="dv">1</span>]<span class="sc">&gt;</span> <span class="fu">length</span>(<span class="fu">na.omit</span>(x))</span>
<span id="cb48-5"><a href="#cb48-5" aria-label="5"></a><span class="co">#&gt; [1] 116</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-label="6"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-label="7"></a>Browse[<span class="dv">1</span>]<span class="sc">&gt;</span> <span class="fu">n_missing</span>(x)</span>
<span id="cb48-8"><a href="#cb48-8" aria-label="8"></a><span class="co">#&gt; [1] 37</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>There it is, and <code>n_missing()</code> was innocent all along.</p>
<p><code>na.omit()</code> has thrown away the very rows we are trying to count, so we divided 37 by 116 instead of by 153. A proportion has to divide by everything, not by what is left over.</p>
<p>Notice how little work that took. Three questions, asked of real objects, in the place where they actually exist.</p>
<p>A few commands are worth knowing at that prompt:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>type this</th>
<th>and it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>n</code></td>
<td>run the next line</td>
</tr>
<tr class="even">
<td><code>c</code></td>
<td>continue until the function ends</td>
</tr>
<tr class="odd">
<td><code>Q</code></td>
<td>quit, and go back to your console</td>
</tr>
<tr class="even">
<td><code>help</code></td>
<td>print the list of these commands</td>
</tr>
<tr class="odd">
<td>anything else</td>
<td>evaluated as ordinary R, in the function’s environment</td>
</tr>
</tbody>
</table>
<p>That last row is the one that matters. Anything you would normally type at the console works here, which means you already know how to use a debugger. You just have to get inside one.</p>
<p><strong>The catch with <code>browser()</code> is that it is committed code.</strong> It stops your script, and it will stop it for whoever runs it next, so you have to remember to take it out again.</p>
<div class="callout callout-style-default callout-note callout-titled" title="We do this one live">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>We do this one live
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reading about a debugger is close to useless. This is a demonstration in the session - I will put us inside a function, and we will poke at it together.</p>
<p>If you are reading this on your own afterwards, run the Your Turn below rather than just reading it. The whole skill is in the doing.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Without editing the function: debugonce(), debug() and undebug()">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Without editing the function: debugonce(), debug() and undebug()
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Editing a function to add <code>browser()</code>, saving, sourcing, and then remembering to take it out again is a lot of steps. There is a way to do the same thing from the console.</p>
<p><strong><code>debugonce()</code></strong> says: next time this function runs, stop at the first line. Once only, so there is nothing to undo.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-label="1"></a><span class="fu">debugonce</span>(prop_missing)</span>
<span id="cb49-2"><a href="#cb49-2" aria-label="2"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-label="3"></a><span class="fu">prop_missing</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb49-4"><a href="#cb49-4" aria-label="4"></a><span class="co">#&gt; debugging in: prop_missing(airquality$Ozone)</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-label="5"></a><span class="co">#&gt; Browse[1]&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Same prompt, same commands, no edit to the function and nothing left behind.</p>
<p><strong><code>debug()</code> and <code>undebug()</code></strong> are the version that stays on. <code>debug()</code> marks the function, and it stays marked until you call <code>undebug()</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-label="1"></a><span class="fu">debug</span>(prop_missing)</span>
<span id="cb50-2"><a href="#cb50-2" aria-label="2"></a><span class="fu">undebug</span>(prop_missing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>That is occasionally what you want, when you are stepping through the same function over and over. Mostly it is not. I’ve forgotten to call <code>undebug()</code> and felt a genuine madness descend as every subsequent call dropped me into the debugger.</p>
<p>So of the two, reach for <code>debugonce()</code>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Your Turn">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn
</div>
</div>
<div class="callout-body-container callout-body">
<p>Your turn to find one. This set also runs, also warns about nothing, and also gives you a plausible number.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-label="1"></a>n_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb51-2"><a href="#cb51-2" aria-label="2"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(x))</span>
<span id="cb51-3"><a href="#cb51-3" aria-label="3"></a>}</span>
<span id="cb51-4"><a href="#cb51-4" aria-label="4"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-label="5"></a>n_complete <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb51-6"><a href="#cb51-6" aria-label="6"></a>  <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x))</span>
<span id="cb51-7"><a href="#cb51-7" aria-label="7"></a>}</span>
<span id="cb51-8"><a href="#cb51-8" aria-label="8"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-label="9"></a>prop_complete <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">digits =</span> <span class="dv">2</span>) {</span>
<span id="cb51-10"><a href="#cb51-10" aria-label="10"></a>  <span class="fu">round</span>(<span class="fu">n_missing</span>(x) <span class="sc">/</span> <span class="fu">length</span>(x), digits)</span>
<span id="cb51-11"><a href="#cb51-11" aria-label="11"></a>}</span>
<span id="cb51-12"><a href="#cb51-12" aria-label="12"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-label="13"></a><span class="fu">prop_complete</span>(airquality<span class="sc">$</span>Ozone)</span>
<span id="cb51-14"><a href="#cb51-14" aria-label="14"></a><span class="co">#&gt; [1] 0.24</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ol type="1">
<li>Before you run anything. <code>airquality$Ozone</code> has 153 values and 37 of them are missing. Does <code>0.24</code> look like the proportion that is <strong>complete</strong>?</li>
<li>Run <code>debugonce(prop_complete)</code>, then call it again. You will land inside the function.</li>
<li>Ask it questions. <code>length(x)</code>, then <code>n_missing(x)</code>, then <code>n_complete(x)</code>. Which two of those belong in this calculation?</li>
<li>Type <code>Q</code> to quit, fix the function, and run it again. You should get <code>0.76</code>.</li>
<li>Do it once more, and this time step through with <code>n</code> rather than quitting.</li>
</ol>
<p>Three functions, and the broken one is not the one doing the arithmetic you would suspect.</p>
<p>Then do the same on a function of your own that you don’t entirely trust.</p>
<p>The habit worth building: when a function surprises you, your first move is <code>debugonce()</code>, not copying the body into a new script.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Read more">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Read more
</div>
</div>
<div class="callout-body-container callout-body">
<p>Parts of this chapter are adapted from my blog post, <a href="https://www.njtierney.com/posts/2023-10-30-how-to-get-good-with-r/">How to get good with R</a>.</p>
<p>The function design walkthrough, and the argument that DRY treats the symptom rather than the cause, come from my talk <strong>Practical functions: practically magic</strong> - <a href="https://njtierney.github.io/funfun/#/title-slide">slides</a> and <a href="https://github.com/njtierney/funfun">source</a>.</p>
<p>Its take-home messages are worth repeating here. Good functions:</p>
<ol type="1">
<li>Manage <strong>complexity</strong></li>
<li>Explain and express <strong>ideas</strong></li>
<li>Can be <strong>individually reasoned</strong> with</li>
<li>Take <strong>iteration</strong></li>
</ol>
</div>
</div>
</section>
</section>
<section id="where-this-script-goes-next" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="where-this-script-goes-next"><span class="header-section-number">4.5</span> Where this script goes next</h2>
<p>We chunked a hundred line script back in <a href="./writing-readable-code.html#sec-de-chunking">Writing readable code</a>, and left it with six comments in it, one per idea.</p>
<p>Once each of those ideas is a function with a name, the whole script is this:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-label="1"></a><span class="fu">source</span>(<span class="st">"packages.R"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-label="2"></a><span class="fu">lapply</span>(<span class="fu">list.files</span>(<span class="st">"./R"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>), source)</span>
<span id="cb52-3"><a href="#cb52-3" aria-label="3"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-label="4"></a>educated_population_2014 <span class="ot">&lt;-</span> <span class="fu">read_educated_population</span>(<span class="at">year =</span> <span class="st">"2014"</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-label="5"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-label="6"></a><span class="fu">ggplot</span>(educated_population_2014, <span class="fu">aes</span>(<span class="at">x =</span> prop_studying, <span class="at">y =</span> state_territory)) <span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-label="7"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-label="8"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ninety lines to six. The other eighty-four did not disappear. They moved into <code>R/</code>, one file per function, exactly the layout from <a href="project-organisation.html" class="quarto-xref">Project organisation&nbsp;<span>1</span></a>.</p>
<p>Getting there is a whole chapter of its own, and it is <a href="appendix-designing-functions.html" class="quarto-xref">Designing functions&nbsp;<span>A</span></a>. That is where we take this script apart a chunk at a time, and where the two identical steps become one function called twice.</p>
</section>
<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<ol type="1">
<li>Functions are for taking something complicated and giving it a clear name.</li>
<li>Name a function for what it does, not how it does it. <code>celcius_to_fahrenheit()</code>, not <code>myfun()</code>.</li>
<li>The parts that change between uses are the arguments. The parts that usually don’t are defaults.</li>
<li>Small functions build on each other. <code>prop_missing()</code> calls <code>n_missing()</code> rather than repeating it.</li>
<li>When a function surprises you, look inside it with <code>debugonce()</code>.</li>
</ol>
<p>If you remember nothing else from this chapter, remember the first one. <strong>Functions are for taking something complicated and giving it a clear name.</strong></p>


</section>
<section class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="">Links</h2>
<ul>
<li><a href="https://r4ds.hadley.nz/functions.html">R for Data Science</a></li>
<li><a href="https://purrr.tidyverse.org/"><code>purrr</code></a></li>
<li><a href="#anatomy-of-a-function">Anatomy of a function</a></li>
<li><a href="https://www.njtierney.com/posts/2023-10-30-how-to-get-good-with-r/">How to get good with R</a></li>
<li><a href="https://njtierney.github.io/funfun/#/title-slide">slides</a></li>
<li><a href="https://github.com/njtierney/funfun">source</a></li>
<li><a href="./writing-readable-code.html#sec-de-chunking">Writing readable code</a></li>
</ul>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/r-best-practices\.njtierney\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./writing-readable-code.html" class="pagination-link" aria-label="Writing readable code">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Writing readable code</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./writing-a-reprex-getting-unstuck.html" class="pagination-link" aria-label="Writing a reprex / getting unstuck">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Writing a reprex / getting unstuck</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2026, Nicholas Tierney</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/njtierney/rbestpractices/edit/main/writing-functions.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/njtierney/rbestpractices/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>